source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target ‘BaseProject’ do
pod 'JPush'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/ReducedWeChat'
pod ‘UMengUShare/Social/ReducedQQ'
pod ‘YYKit’
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod ‘AMap3DMap’
pod ‘AMapLocation’
pod ‘AMapSearch’
pod ‘AMapNavi’
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'PopupDialog', '~> 0.5'
pod 'UIImage-ResizeMagick'
use_frameworks!

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
