source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target ‘BaseProject’ do
pod ‘YYKit’
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod ‘AMap3DMap’
pod ‘AMapLocation’
pod ‘AMapSearch’
pod ‘AMapNavi’
pod 'Masonry'
pod 'IQKeyboardManager'
end
